### PR TITLE
Change vendor to something go module friendly

### PR DESCRIPTION
**Pull request by DoomHammer**

### CODE REVIEW

**Comment by JugglerX** [comment]
Hey I dont understand this PR. Maybe we could just update Bootstrap to 5.3.3?

**Comment by DoomHammer** [comment]
This PR solves the problem I had which was that Hugo could not consume this module in its original state. With this PR, I can use the theme with Hugo Modules without issues.

**Comment by JugglerX** [comment]
We shouldnt modify the bootstrap source files.

**Comment by DoomHammer** [comment]
It is only now I realized this PR contains something totally different than I thought it contained. Weird...

**Pull request closed without merging**
