### PR TITLE
Add missing trailing slashes to internal links

### PR DESCRIPTION
**Pull request by zizzfizzix**
This gets rid of unnecessary redirects and thus helps with SEO.

### CODE REVIEW

**Comment by JugglerX** [comment]
I'm not sure if adding trailing slashes to links is a hugo best practice? Could be wrong.

It looks like these links still use {{ .Site.BaseURL }}. This is a bit outdated, they should be replaced to use relative url ie:

```
{{ "services" | relURL }}
```

I'm not aware of the redirect issue, perhaps it's just happening silently without me knowing. But maybe using the relURL will fix it and avoid the trailing slash?

**Comment by zizzfizzix** [comment]
> I'm not sure if adding trailing slashes to links is a hugo best practice? Could be wrong.

Since pretty URLs in Hugo always end with a slash, internal links should point to them in the same way.
> 
> It looks like these links still use {{ .Site.BaseURL }}. This is a bit outdated, they should be replaced to use relative url ie:
> 
> ```
> {{ "services" | relURL }}
> ```
> 
> I'm not aware of the redirect issue, perhaps it's just happening silently without me knowing. But maybe using the relURL will fix it and avoid the trailing slash?

It does indeed happen in a transparent manner with a 301 redirect eg. http://hugo-serif.netlify.com/services -> http://hugo-serif.netlify.com/services/. This adds, however, an unnecessary request to the server.

According to the [documentation for relURL](https://gohugo.io/functions/relurl/):
> absURL and relURL are smart about missing slashes, but they will not add a closing slash to a URL if it is not present.

Which means that it won't just work. The reason behind not adding the missing slash is unknown to me, especially if pretty URLs always have a trailing slash.

The proper way to insert such links would appear to be:
```
{{ "services/" | relURL }}
```

I can amend this PR to use this approach if you'd like.

**Comment by JugglerX** [comment]
I think you are right, the trailing slash is better. Yes I will accept the PR if you update to use relURL. Thanks!

**Comment by zizzfizzix** [comment]
Updated in one other place too

**Pull request merged**
